name: Build Docs

on:
  push:
    branches:
      - main
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: docs
      - uses: everlytic/branch-merge@1.1.2
        with:
          source_ref: main
          target_branch: docs
          commit_message_template: "[Automated] Merged {source_ref} into target {target_branch}"
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm install
      - run: npm run build
      - run: git add --all
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate docs
          branch: docs
          skip_checkout: true
          push_options: "--force"
